# Inserts a blank line between shell prompts
add_newline = false

[nodejs]
disabled = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[gcloud]
disabled = true

[time]
disabled = false
