
class dotfiles ($home = '/tmp/test') {

  $username = hiera('username')
  $gtalk_jid = hiera('gtalk_jid')
  $gtalk_1time_password = hiera('gtalk_1time_password')
  $cern_jid = hiera('cern_jid')
  $cern_nick = hiera('cern_nick')
  $cern_email = hiera('cern_email')
  $cern_user = hiera('cern_user')
  $cern_password = hiera('cern_password')
  $mysql_user = hiera('mysql_user')
  $mysql_password = hiera('mysql_password')

  $files = {
    'msmtprc'              => {
        owner              => $username,
        group              => $username,
        mode               => 0600,
        path               => "${home}/.msmtprc",
        content            => template('dotfiles/msmtprc')},
    'Xresources'           => {
        owner              => $username,
        group              => $username,
        mode               => 0644,
        path               => "${home}/.Xresources",
        content            => template('dotfiles/Xresources')},
    'vimrc'                => {
        owner              => $username,
        group              => $username,
        mode               => 0644,
        path               => "${home}/.vimrc",
        content            => template('dotfiles/vimrc')},
    'zshrc'                => {
        owner              => $username,
        group              => $username,
        mode               => 0644,
        path               => "${home}/.zshrc",
        content            => template('dotfiles/zshrc')},
    'my.cnf'               => {
        owner              => $username,
        group              => $username,
        mode               => 0600,
        path               => "${home}/.my.cnf",
        content            => template('dotfiles/my.cnf')},
    'psqlrc'               => {
        owner              => $username,
        group              => $username,
        mode               => 0644,
        path               => "${home}/.psqlrc",
        content            => template('dotfiles/psqlrc')},
    'gitconfig'            => {
        owner              => $username,
        group              => $username,
        mode               => 0644,
        path               => "${home}/.gitconfig",
        content            => template('dotfiles/gitconfig')},
    'byobu'                => {
        owner              => $username,
        group              => $username,
        mode               => 0644,
        path               => "${home}/.byobu",
        sourceselect       => all,
        recurse            => true,
        source             => 'puppet:///modules/dotfiles/byobu'},
    'xmonad'               => {
        owner              => $username,
        group              => $username,
        mode               => 0644,
        path               => "${home}/.xmonad",
        sourceselect       => all,
        recurse            => true,
        source             => 'puppet:///modules/dotfiles/xmonad'},
    'mutt'                 => {
        owner              => $username,
        group              => $username,
        mode               => 0644,
        path               => "${home}/.mutt",
        sourceselect       => all,
        recurse            => true,
        source             => 'puppet:///modules/dotfiles/mutt'},
    'mutt-acc-cern'        => {
        owner              => $username,
        group              => $username,
        require            => File['mutt'],
        mode               => 0600,
        path               => "${home}/.mutt/account.cern",
        content            => template('dotfiles/mutt/account.cern')},
    "${home}/.local/"      => {
        owner              => $username,
        group              => $username,
        ensure             => directory,},
    "${home}/.local/share" => {
        owner              => $username,
        group              => $username,
        require            => File["${home}/.local/"],
        ensure             => directory,},
    'profanity-shr'        => {
        owner              => $username,
        group              => $username,
        ensure             => directory,
        require            => File["${home}/.local/share"],
        path               => "${home}/.local/share/profanity",},
    'profanity-acc'        => {
        owner              => $username,
        group              => $username,
        require            => File['profanity-shr'],
        mode               => 0600,
        path               => "${home}/.local/share/profanity/accounts",
        content            => template('dotfiles/local/share/profanity/accounts')},
    "${home}/.config/"     => {
        owner              => $username,
        group              => $username,
        ensure             => directory,},
    'profanity-cnf'        => {
        owner              => $username,
        group              => $username,
        ensure             => directory,
        require            => File["${home}/.config/"],
        path               => "${home}/.config/profanity",},
    'profanity-rc '        => {
        owner              => $username,
        group              => $username,
        require            => File['profanity-cnf'],
        mode               => 0644,
        path               => "${home}/.config/profanity/profrc",
        source             => 'puppet:///modules/dotfiles/config/profanity/profrc'},
    'xmonad-session-rc '   => {
        owner              => $username,
        group              => $username,
        mode               => 0644,
        path               => "${home}/.xmonad/xmonad-session-rc",
        source             => 'puppet:///modules/dotfiles/xmonad/xmonad-session-rc'},
    'xmonad-session '   => {
        owner              => root,
        group              => root,
        mode               => 0644,
        path               => "/usr/bin/xmonad-session",
        source             => 'puppet:///modules/dotfiles/xmonad/xmonad-session'},
    'xmonad.desktop '   => {
        owner              => root,
        group              => root,
        mode               => 0644,
        path               => "/usr/share/xsessions/xmonad.desktop",
        source             => 'puppet:///modules/dotfiles/xmonad/xmonad-desktop'},
  }

  create_resources(file, $files)

}


