#!/usr/bin/env bash

# @raycast.schemaVersion 1
# @raycast.title ec
# @raycast.mode silent
#
# @raycast.packageName icot

if sysctl machdep.cpu.brand_string | grep M1
then
    # M1 based
    /opt/homebrew/bin/emacsclient -c -n
else
    # Intel based Mac
    /usr/local/bin/emacsclient -c -n
fi
