#!/bin/bash

# Required parameters:
# @raycast.schemaVersion 1
# @raycast.title emacsclient
# @raycast.mode silent
#
# Optional parameters:
# @raycast.packageName Emacs
# @raycast.icon images/github-logo.png
# @raycast.iconDark images/github-logo-iconDark.png

emacsclient -c -n
