#!/usr/bin/env bash

# @raycast.schemaVersion 1
# @raycast.title win-left
# @raycast.mode silent
#
# @raycast.packageName icot

swift /Users/icoteril/workspace/swift/spikot-win/spikot-win.swift left


