call pathogen#infect()
syntax on
filetype plugin indent on

let mapleader = ","

set background=dark
set guioptions=i
let g:solarized_termtrans=1
if has("gui_running")
    colorscheme solarized
else
    colorscheme Tomorrow-Night
endif

set autoindent

" Python
set ts=4
set shiftwidth=4
set et
set softtabstop=4

autocmd BufRead *.py set smartindent cinwords=if,elif,else,for,while,try,except,finally,def,class
autocmd BufWritePre *.py normal m`:%s/\s\+$//e ``

function! Mosh_Tab_Or_Complete()
    if col('.')>1 && strpart( getline('.'), col('.')-2, 3 ) =~ '^\w'
        return "\<C-N>"
    else
        return "\<Tab>"
endfunction

:inoremap <Tab> <C-R>=Mosh_Tab_Or_Complete()<CR>
:nnoremap <C-p> :tabprevious<CR>
:nnoremap <C-n> :tabnext<CR>
:nnoremap <C-h> <C-w>h
:nnoremap <C-j> <C-w>j
:nnoremap <C-k> <C-w>k
:nnoremap <C-l> <C-w>l

" Tagbar
:nmap <F8> :TagbarToggle<CR>
let g:tagbar_compact=1
let g:tagbar_autofocus=1

:map <C-t> :NERDTreeToggle<CR>

" Highlight parts of lines longer than 79 columns
au filetype * highlight OverLength ctermbg=darkgreen ctermfg=white guibg=black
au filetype * match OverLength /\%80v.\+/
au BufNewFile,BufRead *.pp setf puppet

" Autosave
:au FocusLost * silent! wa

set laststatus=2
if has("gui_running")
    let g:airline_theme='solarized'
else
    let g:airline_theme='tomorrow'
endif
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = '>'
"let g:airline_powerline_fonts = 1

"" Syntastic
map <silent> <Leader>e :Errors<CR>
map <Leader>s :SyntasticToggleMode<CR>
let g:syntastic_auto_loc_list=0

"" Trying to fix Slow start for YouCompleteMe
let g:ycm_register_as_syntastic_checker = 0

